name: Batalha Épica do CI

on: [push]

jobs:
  batalha:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install pytest

    - name: Iniciar Batalha de Emojis
      run: |
        pytest
